apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached
  namespace: memcached
spec:
  selector:
    matchLabels:
      app: memcached
  replicas: 1
  template:
    metadata:
      labels:
        app: memcached
    spec:
      containers:
      - name: memcached
        image: memcached:1.6.22-alpine
        ports:
        - containerPort: 11211
---
apiVersion: v1
kind: Service
metadata:
  name: memcached
  namespace: memcached
spec:
  selector:
    app: memcached
  ports:
  - port: 11211
    targetPort: 11211