kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kv-mall-infra
rules:
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    resourceNames:
      - privileged
    verbs:
      - use