apiVersion: apps/v1
kind: Deployment
metadata:
  name: coupon
  labels:
    app: coupon
spec:
  selector:
    matchLabels:
      app: coupon
  template:
    metadata:
      labels:
        app: coupon
    spec:
      containers:
      - name: coupon
        image: dev/coupon:dev
        env:
          - name: MEMBERSHIP_SERVICE_URL
            value: "membership:8080"
          - name: KAFKA_ADDRESS
            value: "kafka-service.kv-mall-infra:9092"
        ports:
        - containerPort: 8080

  